# Generated by Django 4.2.4 on 2023-08-18 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "news_app",
            "0002_remove_history_content_type_remove_history_object_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="viewed_on",
        ),
        migrations.AddField(
            model_name="history",
            name="keyword",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="history",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="urls",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 0, 24, 18, 5333)
            ),
        ),
    ]
