# Generated by Django 4.2.4 on 2023-08-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_remove_history_viewed_on_history_keyword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="keyword",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 0, 36, 19, 853200)
            ),
        ),
    ]
