# Generated by Django 4.2.4 on 2023-08-21 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_alter_history_keyword_alter_news_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 15, 18, 57, 40212)
            ),
        ),
        migrations.DeleteModel(
            name="History",
        ),
    ]
